/*
 * Copyright 2022 Keyfactor
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.  You may obtain a
 * copy of the License at http://www.apache.org/licenses/LICENSE-2.0.  Unless
 * required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
 * OR CONDITIONS OF ANY KIND, either express or implied. See the License for
 * thespecific language governing permissions and limitations under the
 * License.
 *
 * EJBCA REST Interface
 * API reference documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keyfactor.ejbca.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.keyfactor.ejbca.client.JSON;

/**
 * CertificateProfileInfoRestResponseV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-08T11:12:50.631-07:00[America/Phoenix]")
public class CertificateProfileInfoRestResponseV2 {
  public static final String SERIALIZED_NAME_AVAILABLE_KEY_ALGS = "available_key_algs";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_KEY_ALGS)
  private List<String> availableKeyAlgs = null;

  public static final String SERIALIZED_NAME_AVAILABLE_BIT_LENGHTS = "available_bit_lenghts";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_BIT_LENGHTS)
  private List<Integer> availableBitLenghts = null;

  public static final String SERIALIZED_NAME_AVAILABLE_ECDSA_CURVES = "available_ecdsa_curves";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_ECDSA_CURVES)
  private List<String> availableEcdsaCurves = null;

  public static final String SERIALIZED_NAME_AVAILABLE_CAS = "available_cas";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_CAS)
  private List<String> availableCas = null;

  public CertificateProfileInfoRestResponseV2() {
  }

  public CertificateProfileInfoRestResponseV2 availableKeyAlgs(List<String> availableKeyAlgs) {
    
    this.availableKeyAlgs = availableKeyAlgs;
    return this;
  }

  public CertificateProfileInfoRestResponseV2 addAvailableKeyAlgsItem(String availableKeyAlgsItem) {
    if (this.availableKeyAlgs == null) {
      this.availableKeyAlgs = new ArrayList<>();
    }
    this.availableKeyAlgs.add(availableKeyAlgsItem);
    return this;
  }

   /**
   * Get availableKeyAlgs
   * @return availableKeyAlgs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAvailableKeyAlgs() {
    return availableKeyAlgs;
  }


  public void setAvailableKeyAlgs(List<String> availableKeyAlgs) {
    this.availableKeyAlgs = availableKeyAlgs;
  }


  public CertificateProfileInfoRestResponseV2 availableBitLenghts(List<Integer> availableBitLenghts) {
    
    this.availableBitLenghts = availableBitLenghts;
    return this;
  }

  public CertificateProfileInfoRestResponseV2 addAvailableBitLenghtsItem(Integer availableBitLenghtsItem) {
    if (this.availableBitLenghts == null) {
      this.availableBitLenghts = new ArrayList<>();
    }
    this.availableBitLenghts.add(availableBitLenghtsItem);
    return this;
  }

   /**
   * Get availableBitLenghts
   * @return availableBitLenghts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getAvailableBitLenghts() {
    return availableBitLenghts;
  }


  public void setAvailableBitLenghts(List<Integer> availableBitLenghts) {
    this.availableBitLenghts = availableBitLenghts;
  }


  public CertificateProfileInfoRestResponseV2 availableEcdsaCurves(List<String> availableEcdsaCurves) {
    
    this.availableEcdsaCurves = availableEcdsaCurves;
    return this;
  }

  public CertificateProfileInfoRestResponseV2 addAvailableEcdsaCurvesItem(String availableEcdsaCurvesItem) {
    if (this.availableEcdsaCurves == null) {
      this.availableEcdsaCurves = new ArrayList<>();
    }
    this.availableEcdsaCurves.add(availableEcdsaCurvesItem);
    return this;
  }

   /**
   * Get availableEcdsaCurves
   * @return availableEcdsaCurves
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAvailableEcdsaCurves() {
    return availableEcdsaCurves;
  }


  public void setAvailableEcdsaCurves(List<String> availableEcdsaCurves) {
    this.availableEcdsaCurves = availableEcdsaCurves;
  }


  public CertificateProfileInfoRestResponseV2 availableCas(List<String> availableCas) {
    
    this.availableCas = availableCas;
    return this;
  }

  public CertificateProfileInfoRestResponseV2 addAvailableCasItem(String availableCasItem) {
    if (this.availableCas == null) {
      this.availableCas = new ArrayList<>();
    }
    this.availableCas.add(availableCasItem);
    return this;
  }

   /**
   * Get availableCas
   * @return availableCas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAvailableCas() {
    return availableCas;
  }


  public void setAvailableCas(List<String> availableCas) {
    this.availableCas = availableCas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateProfileInfoRestResponseV2 certificateProfileInfoRestResponseV2 = (CertificateProfileInfoRestResponseV2) o;
    return Objects.equals(this.availableKeyAlgs, certificateProfileInfoRestResponseV2.availableKeyAlgs) &&
        Objects.equals(this.availableBitLenghts, certificateProfileInfoRestResponseV2.availableBitLenghts) &&
        Objects.equals(this.availableEcdsaCurves, certificateProfileInfoRestResponseV2.availableEcdsaCurves) &&
        Objects.equals(this.availableCas, certificateProfileInfoRestResponseV2.availableCas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableKeyAlgs, availableBitLenghts, availableEcdsaCurves, availableCas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateProfileInfoRestResponseV2 {\n");
    sb.append("    availableKeyAlgs: ").append(toIndentedString(availableKeyAlgs)).append("\n");
    sb.append("    availableBitLenghts: ").append(toIndentedString(availableBitLenghts)).append("\n");
    sb.append("    availableEcdsaCurves: ").append(toIndentedString(availableEcdsaCurves)).append("\n");
    sb.append("    availableCas: ").append(toIndentedString(availableCas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("available_key_algs");
    openapiFields.add("available_bit_lenghts");
    openapiFields.add("available_ecdsa_curves");
    openapiFields.add("available_cas");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CertificateProfileInfoRestResponseV2
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (CertificateProfileInfoRestResponseV2.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in CertificateProfileInfoRestResponseV2 is not found in the empty JSON string", CertificateProfileInfoRestResponseV2.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CertificateProfileInfoRestResponseV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CertificateProfileInfoRestResponseV2` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if ((jsonObj.get("available_key_algs") != null && !jsonObj.get("available_key_algs").isJsonNull()) && !jsonObj.get("available_key_algs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_key_algs` to be an array in the JSON string but got `%s`", jsonObj.get("available_key_algs").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("available_bit_lenghts") != null && !jsonObj.get("available_bit_lenghts").isJsonNull()) && !jsonObj.get("available_bit_lenghts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_bit_lenghts` to be an array in the JSON string but got `%s`", jsonObj.get("available_bit_lenghts").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("available_ecdsa_curves") != null && !jsonObj.get("available_ecdsa_curves").isJsonNull()) && !jsonObj.get("available_ecdsa_curves").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_ecdsa_curves` to be an array in the JSON string but got `%s`", jsonObj.get("available_ecdsa_curves").toString()));
      }
      // ensure the json data is an array
      if ((jsonObj.get("available_cas") != null && !jsonObj.get("available_cas").isJsonNull()) && !jsonObj.get("available_cas").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `available_cas` to be an array in the JSON string but got `%s`", jsonObj.get("available_cas").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CertificateProfileInfoRestResponseV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CertificateProfileInfoRestResponseV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CertificateProfileInfoRestResponseV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CertificateProfileInfoRestResponseV2.class));

       return (TypeAdapter<T>) new TypeAdapter<CertificateProfileInfoRestResponseV2>() {
           @Override
           public void write(JsonWriter out, CertificateProfileInfoRestResponseV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CertificateProfileInfoRestResponseV2 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CertificateProfileInfoRestResponseV2 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CertificateProfileInfoRestResponseV2
  * @throws IOException if the JSON string is invalid with respect to CertificateProfileInfoRestResponseV2
  */
  public static CertificateProfileInfoRestResponseV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CertificateProfileInfoRestResponseV2.class);
  }

 /**
  * Convert an instance of CertificateProfileInfoRestResponseV2 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

