/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keyfactor.ejbca.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.keyfactor.ejbca.client.model.SearchEndEntitiesSortRestRequest;
import com.keyfactor.ejbca.client.model.SearchEndEntityCriteriaRestRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.keyfactor.ejbca.client.JSON;

/**
 * SearchEndEntitiesRestRequestV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-27T00:18:55.030-07:00[America/Phoenix]")
public class SearchEndEntitiesRestRequestV2 {
  public static final String SERIALIZED_NAME_MAX_NUMBER_OF_RESULTS = "max_number_of_results";
  @SerializedName(SERIALIZED_NAME_MAX_NUMBER_OF_RESULTS)
  private Integer maxNumberOfResults;

  public static final String SERIALIZED_NAME_CURRENT_PAGE = "current_page";
  @SerializedName(SERIALIZED_NAME_CURRENT_PAGE)
  private Integer currentPage;

  public static final String SERIALIZED_NAME_CRITERIA = "criteria";
  @SerializedName(SERIALIZED_NAME_CRITERIA)
  private List<SearchEndEntityCriteriaRestRequest> criteria = null;

  public static final String SERIALIZED_NAME_SORT_OPERATION = "sort_operation";
  @SerializedName(SERIALIZED_NAME_SORT_OPERATION)
  private SearchEndEntitiesSortRestRequest sortOperation;

  public SearchEndEntitiesRestRequestV2() {
  }

  public SearchEndEntitiesRestRequestV2 maxNumberOfResults(Integer maxNumberOfResults) {
    
    this.maxNumberOfResults = maxNumberOfResults;
    return this;
  }

   /**
   * Maximum number of results
   * @return maxNumberOfResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "Maximum number of results")

  public Integer getMaxNumberOfResults() {
    return maxNumberOfResults;
  }


  public void setMaxNumberOfResults(Integer maxNumberOfResults) {
    this.maxNumberOfResults = maxNumberOfResults;
  }


  public SearchEndEntitiesRestRequestV2 currentPage(Integer currentPage) {
    
    this.currentPage = currentPage;
    return this;
  }

   /**
   * Current page number
   * @return currentPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "Current page number")

  public Integer getCurrentPage() {
    return currentPage;
  }


  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }


  public SearchEndEntitiesRestRequestV2 criteria(List<SearchEndEntityCriteriaRestRequest> criteria) {
    
    this.criteria = criteria;
    return this;
  }

  public SearchEndEntitiesRestRequestV2 addCriteriaItem(SearchEndEntityCriteriaRestRequest criteriaItem) {
    if (this.criteria == null) {
      this.criteria = new ArrayList<>();
    }
    this.criteria.add(criteriaItem);
    return this;
  }

   /**
   * A List of search criteria.
   * @return criteria
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A List of search criteria.")

  public List<SearchEndEntityCriteriaRestRequest> getCriteria() {
    return criteria;
  }


  public void setCriteria(List<SearchEndEntityCriteriaRestRequest> criteria) {
    this.criteria = criteria;
  }


  public SearchEndEntitiesRestRequestV2 sortOperation(SearchEndEntitiesSortRestRequest sortOperation) {
    
    this.sortOperation = sortOperation;
    return this;
  }

   /**
   * Get sortOperation
   * @return sortOperation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SearchEndEntitiesSortRestRequest getSortOperation() {
    return sortOperation;
  }


  public void setSortOperation(SearchEndEntitiesSortRestRequest sortOperation) {
    this.sortOperation = sortOperation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchEndEntitiesRestRequestV2 searchEndEntitiesRestRequestV2 = (SearchEndEntitiesRestRequestV2) o;
    return Objects.equals(this.maxNumberOfResults, searchEndEntitiesRestRequestV2.maxNumberOfResults) &&
        Objects.equals(this.currentPage, searchEndEntitiesRestRequestV2.currentPage) &&
        Objects.equals(this.criteria, searchEndEntitiesRestRequestV2.criteria) &&
        Objects.equals(this.sortOperation, searchEndEntitiesRestRequestV2.sortOperation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxNumberOfResults, currentPage, criteria, sortOperation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchEndEntitiesRestRequestV2 {\n");
    sb.append("    maxNumberOfResults: ").append(toIndentedString(maxNumberOfResults)).append("\n");
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("    sortOperation: ").append(toIndentedString(sortOperation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("max_number_of_results");
    openapiFields.add("current_page");
    openapiFields.add("criteria");
    openapiFields.add("sort_operation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SearchEndEntitiesRestRequestV2
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SearchEndEntitiesRestRequestV2.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchEndEntitiesRestRequestV2 is not found in the empty JSON string", SearchEndEntitiesRestRequestV2.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SearchEndEntitiesRestRequestV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchEndEntitiesRestRequestV2` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("criteria") != null && !jsonObj.get("criteria").isJsonNull()) {
        JsonArray jsonArraycriteria = jsonObj.getAsJsonArray("criteria");
        if (jsonArraycriteria != null) {
          // ensure the json data is an array
          if (!jsonObj.get("criteria").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `criteria` to be an array in the JSON string but got `%s`", jsonObj.get("criteria").toString()));
          }

          // validate the optional field `criteria` (array)
          for (int i = 0; i < jsonArraycriteria.size(); i++) {
            SearchEndEntityCriteriaRestRequest.validateJsonObject(jsonArraycriteria.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `sort_operation`
      if (jsonObj.get("sort_operation") != null && !jsonObj.get("sort_operation").isJsonNull()) {
        SearchEndEntitiesSortRestRequest.validateJsonObject(jsonObj.getAsJsonObject("sort_operation"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchEndEntitiesRestRequestV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchEndEntitiesRestRequestV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchEndEntitiesRestRequestV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchEndEntitiesRestRequestV2.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchEndEntitiesRestRequestV2>() {
           @Override
           public void write(JsonWriter out, SearchEndEntitiesRestRequestV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchEndEntitiesRestRequestV2 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SearchEndEntitiesRestRequestV2 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SearchEndEntitiesRestRequestV2
  * @throws IOException if the JSON string is invalid with respect to SearchEndEntitiesRestRequestV2
  */
  public static SearchEndEntitiesRestRequestV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchEndEntitiesRestRequestV2.class);
  }

 /**
  * Convert an instance of SearchEndEntitiesRestRequestV2 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

