/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keyfactor.ejbca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.keyfactor.ejbca.client.JSON;

/**
 * PaginationRestResponseComponent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-26T23:53:22.978-07:00[America/Phoenix]")
public class PaginationRestResponseComponent {
  public static final String SERIALIZED_NAME_MORE_RESULTS = "more_results";
  @SerializedName(SERIALIZED_NAME_MORE_RESULTS)
  private Boolean moreResults;

  public static final String SERIALIZED_NAME_NEXT_OFFSET = "next_offset";
  @SerializedName(SERIALIZED_NAME_NEXT_OFFSET)
  private Integer nextOffset;

  public static final String SERIALIZED_NAME_NUMBER_OF_RESULTS = "number_of_results";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_RESULTS)
  private Integer numberOfResults;

  public PaginationRestResponseComponent() {
  }

  public PaginationRestResponseComponent moreResults(Boolean moreResults) {
    
    this.moreResults = moreResults;
    return this;
  }

   /**
   * Get moreResults
   * @return moreResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMoreResults() {
    return moreResults;
  }


  public void setMoreResults(Boolean moreResults) {
    this.moreResults = moreResults;
  }


  public PaginationRestResponseComponent nextOffset(Integer nextOffset) {
    
    this.nextOffset = nextOffset;
    return this;
  }

   /**
   * Get nextOffset
   * @return nextOffset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNextOffset() {
    return nextOffset;
  }


  public void setNextOffset(Integer nextOffset) {
    this.nextOffset = nextOffset;
  }


  public PaginationRestResponseComponent numberOfResults(Integer numberOfResults) {
    
    this.numberOfResults = numberOfResults;
    return this;
  }

   /**
   * Get numberOfResults
   * @return numberOfResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getNumberOfResults() {
    return numberOfResults;
  }


  public void setNumberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationRestResponseComponent paginationRestResponseComponent = (PaginationRestResponseComponent) o;
    return Objects.equals(this.moreResults, paginationRestResponseComponent.moreResults) &&
        Objects.equals(this.nextOffset, paginationRestResponseComponent.nextOffset) &&
        Objects.equals(this.numberOfResults, paginationRestResponseComponent.numberOfResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moreResults, nextOffset, numberOfResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationRestResponseComponent {\n");
    sb.append("    moreResults: ").append(toIndentedString(moreResults)).append("\n");
    sb.append("    nextOffset: ").append(toIndentedString(nextOffset)).append("\n");
    sb.append("    numberOfResults: ").append(toIndentedString(numberOfResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("more_results");
    openapiFields.add("next_offset");
    openapiFields.add("number_of_results");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaginationRestResponseComponent
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PaginationRestResponseComponent.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaginationRestResponseComponent is not found in the empty JSON string", PaginationRestResponseComponent.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PaginationRestResponseComponent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PaginationRestResponseComponent` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaginationRestResponseComponent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaginationRestResponseComponent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaginationRestResponseComponent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaginationRestResponseComponent.class));

       return (TypeAdapter<T>) new TypeAdapter<PaginationRestResponseComponent>() {
           @Override
           public void write(JsonWriter out, PaginationRestResponseComponent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaginationRestResponseComponent read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaginationRestResponseComponent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaginationRestResponseComponent
  * @throws IOException if the JSON string is invalid with respect to PaginationRestResponseComponent
  */
  public static PaginationRestResponseComponent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaginationRestResponseComponent.class);
  }

 /**
  * Convert an instance of PaginationRestResponseComponent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

